### ISSUE TITLE
Crashing during SVS

### ISSUE THREAD

**Issue by LivesParkkk** [GingerWalnut/SQBeyondPublic#30] opened 2019-02-24 21:37 UTC
I noticed that during svs I was crashing alot. It shouldn't be a problem with my PC, i have above average specs. This is the error i get:

The game crashed whilst rendering block entity
The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: Cannot get property bme{name=facing, clazz=class eq, values=[north, south, west, east]} as it does not exist in Block{minecraft:hopper}

I have the full crash log and I can upload that if needed.

This occured with 2 people flying, and seemed to happen alot if multiple cannons were being fired at the same time. I could also reproduce it occasionally by rotating my ship.

**Comment by Jarkyc** [comment] 2019-02-24 21:57
Can confirm this, I crashed for the same reasons. Maybe related to my bug i submitted on crashing

**Comment by GingerWalnut** [comment] 2019-02-24 23:57
duplicate of #13

**Closed by GingerWalnut** 2019-02-24 23:57 UTC
