### ISSUE TITLE
Add warnings to the chat plugin

### ISSUE THREAD

**Issue by Seamonster778778778788** [GingerWalnut/SQBeyondPublic#420] opened 2019-09-07 20:23 UTC
Add a warning to the chat plugin that lets mods warn people
/warn player reason expiration date of warning

make it /title subtitle/something and saying You have been warned for "______"

**Comment by Jarkyc** [comment] 2019-09-07 20:41
Duplicate of #340

**Comment by Jarkyc** [comment] 2019-09-07 20:42
I will be making a separate SQStaffTools plugin for stuff like this.

**Closed by Jarkyc** 2019-09-07 20:42 UTC
Labels: suggestion
